In [3]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.linear_model import LogisticRegression, LogisticRegressionCV
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, RobustScaler, LabelEncoder, OneHotEncoder
from sklearn.pipeline import make_pipeline
from sklearn.metrics import roc_auc_score, roc_curve

from google.colab import files
uploaded = files.upload()


Saving data.csv to data (1).csv


In [4]:
data = pd.read_csv('data.csv')
data = data.iloc[:, 1:5]
print(data)

        real  predict1  predict2  predict3
0       26.5     25.18     25.54     24.96
1       26.6     26.59     26.07     26.47
2       27.3     26.58     26.94     26.98
3       27.5     26.80     26.93     26.69
4       27.5     28.46     28.27     27.60
...      ...       ...       ...       ...
376813  24.7     24.78     24.95     24.92
376814  24.2     24.38     24.37     24.64
376815  23.9     24.35     24.23     23.94
376816  23.4     23.60     23.96     23.85
376817  23.5     23.54     23.50     23.58

[376818 rows x 4 columns]


In [5]:
data = data[(data['real'] > 0) & (data['real'] < 50)]
X = data.iloc[:, 1:5]
y = data[:]['real']
print(X.values)
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=42)
print(X_train)
print(y_train)

[[25.18 25.54 24.96]
 [26.59 26.07 26.47]
 [26.58 26.94 26.98]
 ...
 [24.35 24.23 23.94]
 [23.6  23.96 23.85]
 [23.54 23.5  23.58]]
        predict1  predict2  predict3
180033     17.13     18.00     17.09
154181     18.47     17.78     17.77
178958     33.15     33.16     33.12
215212     22.22     22.21     22.33
351582     21.13     21.19     21.55
...          ...       ...       ...
132651     24.21     23.92     24.21
294322     31.28     31.59     31.34
145399     15.75     17.28     15.35
162213     22.05     22.01     21.74
134734     26.17     26.12     28.05

[272079 rows x 3 columns]
180033    18.5
154181    17.7
178958    33.6
215212    22.1
351582    21.0
          ... 
132651    23.7
294322    31.7
145399    15.4
162213    22.1
134734    25.8
Name: real, Length: 272079, dtype: float64


In [6]:
!pip install catboost

In [7]:
from catboost import CatBoostRegressor
model = CatBoostRegressor(n_estimators=1200, learning_rate=0.1)

model.fit(
    X_train, y_train
)
print('Model is fitted: ' + str(model.is_fitted()))
print('Model params:')
print(model.get_params())

0:	learn: 4.5372339	total: 84.8ms	remaining: 1m 41s
1:	learn: 4.1308429	total: 116ms	remaining: 1m 9s
2:	learn: 3.7642128	total: 147ms	remaining: 58.5s
3:	learn: 3.4365740	total: 178ms	remaining: 53.1s
4:	learn: 3.1419305	total: 212ms	remaining: 50.6s
5:	learn: 2.8759496	total: 243ms	remaining: 48.4s
6:	learn: 2.6371400	total: 274ms	remaining: 46.7s
7:	learn: 2.4281806	total: 308ms	remaining: 45.9s
8:	learn: 2.2389105	total: 339ms	remaining: 44.9s
9:	learn: 2.0706884	total: 370ms	remaining: 44.1s
10:	learn: 1.9205574	total: 402ms	remaining: 43.4s
11:	learn: 1.7878933	total: 433ms	remaining: 42.9s
12:	learn: 1.6718742	total: 464ms	remaining: 42.4s
13:	learn: 1.5697475	total: 495ms	remaining: 42s
14:	learn: 1.4809465	total: 531ms	remaining: 42s
15:	learn: 1.4031274	total: 562ms	remaining: 41.6s
16:	learn: 1.3351065	total: 590ms	remaining: 41.1s
17:	learn: 1.2760500	total: 621ms	remaining: 40.8s
18:	learn: 1.2262343	total: 653ms	remaining: 40.6s
19:	learn: 1.1837319	total: 684ms	remaining

In [8]:
y_train_predicted = model.predict(X_train)
y_test_predicted = model.predict(X_test)
print(y_test_predicted)
print(y_test.values)

[27.31651058 23.05796995 23.50770342 ... 27.3353405  23.47581458
 22.71256281]
[26.  23.1 23.4 ... 25.5 22.7 23.2]


In [9]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test_predicted, y_test)

0.8901959424484

In [10]:
model.save_model("model.json", format="json")

In [11]:
files.download("model.json")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>